'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { AlertTriangle, ArrowLeft, Building2, RefreshCw } from 'lucide-react'

type Metric={code:string;value:number|null;target:number|null;compliance:number|null;mom:number|null;yoy:number|null;unit:string;comparisonValue?:number|null;comparisonPeriod?:string|null;qualityNotes?:string[];methodology?:string}
type Evolution={period:string;sales:number|null;salesTarget:number|null}
type Entity={id:string;name:string;entityType:string;parentId:string|null;metrics:Metric[];evolution?:Evolution[]}
type Summary={periodLabel:string;generatedAt?:string;dataProvenance?:string;entities:Entity[]}
type Operations={valuations:{review:number};tasks:{overdue:number;urgent:number};assignments:{paused:number};market:{pendingIdentity:number}}
const metric=(entity:Entity|undefined,code:string)=>entity?.metrics.find((item)=>item.code===code)
const fmt=(item?:Metric)=>!item||item.value==null?'n/d':item.unit==='uf'?`${item.value.toLocaleString('es-CL',{maximumFractionDigits:0})} UF`:item.value.toLocaleString('es-CL',{maximumFractionDigits:1})
const pct=(value:number|null|undefined)=>value==null?'n/d':`${value>0?'+':''}${value.toFixed(1)}%`
const compliance=(item?:Metric)=>item?.compliance==null?'n/d':`${item.compliance.toFixed(1)}%`
const base=(item?:Metric)=>item?.comparisonValue==null?'Base 2025 n/d':item.unit==='uf'?`${item.comparisonValue.toLocaleString('es-CL',{maximumFractionDigits:0})} UF en 2025`:`${item.comparisonValue.toLocaleString('es-CL',{maximumFractionDigits:1})} en 2025`

export function CeoPresentation(){
  const [summary,setSummary]=useState<Summary|null>(null)
  const [operations,setOperations]=useState<Operations|null>(null)
  const [error,setError]=useState<string|null>(null)
  useEffect(()=>{void(async()=>{try{const [s,o]=await Promise.all([fetch('/api/management/summary',{cache:'no-store'}),fetch('/api/management/ceo-operations',{cache:'no-store'})]);const [sd,od]=await Promise.all([s.json(),o.json()]);if(!s.ok||!o.ok)throw new Error(sd.error||od.error||'No fue posible cargar la presentación.');setSummary(sd);setOperations(od)}catch(cause){setError(cause instanceof Error?cause.message:'Error de carga')}})()},[])
  const company=summary?.entities.find((entity)=>entity.entityType==='company')
  const branches=summary?.entities.filter((entity)=>entity.entityType==='branch')??[]
  const partners=summary?.entities.filter((entity)=>entity.entityType==='partner')??[]
  const ordered=useMemo(()=>[...branches].sort((a,b)=>Number(metric(b,'sales')?.compliance??-1)-Number(metric(a,'sales')?.compliance??-1)),[branches])
  const ranking=useMemo(()=>[...partners].sort((a,b)=>Number(metric(b,'sales')?.value??-1)-Number(metric(a,'sales')?.value??-1)).slice(0,5),[partners])
  const sales=metric(company,'sales'),uf=metric(company,'sales_uf'),cum=metric(company,'cumulative_sales'),cumUf=metric(company,'cumulative_sales_uf'),stock=metric(company,'stock'),movement=metric(company,'portfolio_net_change')
  const followUp=metric(company,'follow_up_score'),conversion=metric(company,'conversion')
  const productivityProxy=sales?.value!=null&&partners.length?sales.value/partners.length:null
  const evolution=company?.evolution??[];const max=Math.max(1,...evolution.flatMap((item)=>[item.sales??0,item.salesTarget??0]))
  const actionPending=operations?operations.tasks.overdue+operations.valuations.review+operations.assignments.paused:0
  const dataBacklog=operations?.market.pendingIdentity??0
  const qualityNotes=[...(sales?.qualityNotes??[]),...(uf?.qualityNotes??[]),...(cum?.qualityNotes??[]),...(cumUf?.qualityNotes??[])]
  return <main className="min-h-screen bg-[var(--n3-black)] px-5 py-6 text-[var(--n3-text-light)] md:px-10 lg:px-14">
    <div className="mb-8 flex flex-wrap items-center justify-between gap-4"><Link href="/dashboard/ceo" className="inline-flex items-center gap-2 text-sm text-[var(--n3-text-muted)] focus-visible:outline focus-visible:outline-2"><ArrowLeft size={16}/>Volver</Link><div className="text-xs uppercase tracking-[0.16em] text-[var(--n3-text-muted)]">{summary?.periodLabel??'Cargando período'} · {summary?.generatedAt?new Date(summary.generatedAt).toLocaleString('es-CL'):'sin actualización'}</div></div>
    {error?<div role="alert" className="border border-[#d7332b] p-6 text-[#ff766f]"><RefreshCw className="mb-3"/>{error}</div>:null}
    {!error&&(!summary||!operations)?<div role="status" className="flex min-h-[60vh] items-center justify-center text-lg text-[var(--n3-text-muted)]">Preparando vista ejecutiva…</div>:null}
    {!error&&summary&&operations?<>
      <header className="mb-10 max-w-5xl"><div className="mb-4 flex items-center gap-3 text-sm uppercase tracking-[0.18em] text-[#ff766f]"><Building2 size={20}/>Presentación ejecutiva contractual</div><h1 className="text-4xl font-semibold leading-tight md:text-6xl">Property Partners en una mirada</h1><p className="mt-5 max-w-4xl text-lg leading-8 text-[var(--n3-text-muted)]">Resultados 2026 comparados con la misma base 2025, metas, evolución, productividad, seguimiento, conversión, cartera y decisiones.</p></header>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[[sales,'Cierres junio'],[uf,'UF junio'],[cum,'Cierres acumulados'],[cumUf,'UF acumuladas']].map(([item,label])=><article key={label as string} className="border border-[var(--n3-line)] bg-[#0c1111] p-6"><p className="text-sm text-[var(--n3-text-muted)]">{label as string}</p><p className="mt-3 text-4xl font-semibold">{fmt(item as Metric)}</p><p className="mt-2 text-sm">YoY {pct((item as Metric)?.yoy)} · {base(item as Metric)}</p></article>)}</section>
      <section className="mt-6 grid gap-4 md:grid-cols-3"><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Meta junio</p><p className="mt-3 text-3xl font-semibold">{compliance(sales)}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">{fmt(sales)} de meta {sales?.target??'n/d'} cierres.</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Movimiento neto de cartera</p><p className="mt-3 text-3xl font-semibold">{fmt(movement)}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">{pct(movement?.yoy)} mayo–junio. Cartera actual {fmt(stock)}. No equivale a captaciones.</p></article><article className={`border bg-[#0c1111] p-5 ${actionPending?'border-[#a77a22]':'border-[#2f8f4e]'}`}><p className="text-sm text-[var(--n3-text-muted)]">Decisiones operativas</p><p className="mt-3 text-3xl font-semibold">{actionPending}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">{operations.tasks.overdue} tareas, {operations.valuations.review} valorizaciones, {operations.assignments.paused} asignaciones pausadas.</p></article></section>
      <section className="mt-10 grid gap-4 md:grid-cols-4"><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Captaciones brutas</p><p className="mt-3 text-3xl font-semibold">n/d</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">No existe una métrica explícita separada de altas, bajas y ventas.</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Seguimiento</p><p className="mt-3 text-3xl font-semibold">{fmt(followUp)}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">Score canónico, no tasa porcentual.</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Conversión</p><p className="mt-3 text-3xl font-semibold">{fmt(conversion)}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">Score canónico, no tasa porcentual.</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Productividad (proxy)</p><p className="mt-3 text-3xl font-semibold">{productivityProxy==null?'n/d':productivityProxy.toFixed(2)}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">Cierres ÷ fichas canónicas visibles.</p></article></section>
      <section className="mt-10"><h2 className="mb-5 text-2xl font-semibold">Evolución cierres / meta</h2>{evolution.length?<div className="grid grid-cols-6 gap-3 border border-[var(--n3-line)] bg-[#0c1111] p-5">{evolution.map((item)=><div key={item.period} className="flex min-h-44 flex-col justify-end"><div className="flex h-28 items-end justify-center gap-1"><div className="w-5 bg-[#d7332b]" style={{height:`${Math.max(3,((item.sales??0)/max)*100)}%`}}/><div className="w-5 bg-white/15" style={{height:`${Math.max(3,((item.salesTarget??0)/max)*100)}%`}}/></div><p className="mt-2 text-center text-xs uppercase text-[var(--n3-text-muted)]">{item.period.slice(5)}</p><p className="text-center text-sm">{item.sales??'n/d'} / {item.salesTarget??'n/d'}</p></div>)}</div>:<div className="border border-dashed border-[var(--n3-line)] p-6 text-[var(--n3-text-muted)]">Sin evolución canónica disponible.</div>}</section>
      <section className="mt-10"><h2 className="mb-5 text-2xl font-semibold">Comparación por oficina</h2><div className="grid gap-4 lg:grid-cols-3">{ordered.map((branch,index)=>{const branchSales=metric(branch,'sales'),branchCum=metric(branch,'cumulative_sales'),branchMovement=metric(branch,'portfolio_net_change');return <article key={branch.id} className="border border-[var(--n3-line)] bg-[#0c1111] p-6"><div className="flex justify-between"><span className="text-xs text-[var(--n3-text-muted)]">#{index+1}</span><span>{compliance(branchSales)}</span></div><h3 className="mt-3 text-2xl font-semibold">{branch.name}</h3><p className="mt-4 text-3xl font-semibold">{fmt(branchSales)}</p><p className="mt-1 text-sm">YoY junio {pct(branchSales?.yoy)} · base {base(branchSales)}</p><div className="mt-5 grid grid-cols-2 gap-3"><div><p className="text-xs text-[var(--n3-text-muted)]">YoY acumulado</p><p className="text-xl">{pct(branchCum?.yoy)}</p></div><div><p className="text-xs text-[var(--n3-text-muted)]">Movimiento cartera</p><p className="text-xl">{fmt(branchMovement)}</p></div></div></article>})}</div></section>
      <section className="mt-10 grid gap-5 lg:grid-cols-[1fr_0.8fr]"><div><h2 className="mb-5 text-2xl font-semibold">Top ejecutivas por cierres</h2><div className="divide-y divide-[var(--n3-line)] border border-[var(--n3-line)] bg-[#0c1111]">{ranking.map((entity,index)=><div key={entity.id} className="flex justify-between p-4"><span>{index+1}. {entity.name}</span><strong>{fmt(metric(entity,'sales'))} · YoY {pct(metric(entity,'sales')?.yoy)}</strong></div>)}</div></div><article className={`border bg-[#0c1111] p-7 ${qualityNotes.length?'border-[#a77a22]':'border-[#2f8f4e]'}`}><div className="flex gap-4"><AlertTriangle className={qualityNotes.length?'text-[#f6c453]':'text-[#65c780]'}/><div><h2 className="text-2xl font-semibold">Control de calidad YoY</h2><p className="mt-3 text-lg leading-8 text-[var(--n3-text-muted)]">{qualityNotes.length?`${qualityNotes.length} diferencia(s) entre cálculo y Δ% AA informado.`:'El YoY recalculado coincide con el porcentaje informado dentro de tolerancia.'}</p>{qualityNotes[0]?<p className="mt-3 text-sm text-[var(--n3-text-muted)]">{qualityNotes[0]}</p>:null}<p className="mt-3 text-sm text-[var(--n3-text-muted)]">Backlog de identidad: {dataBacklog} registros.</p></div></div></article></section>
      <p className="mt-8 text-xs leading-5 text-[var(--n3-text-muted)]">YoY recalculado desde bases 2025 y contrastado con Δ% AA. El movimiento neto de cartera no representa captaciones brutas. Los consolidados y oficinas se reproducen desde fuentes canónicas respectivas.</p>
    </>:null}
  </main>
}
