'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { ArrowLeft, ArrowRight, RefreshCw } from 'lucide-react'
import { IntelligenceHeader, IntelligencePage, MetricCard, MetricGrid, SectionHeading } from '@/components/intelligence/design-system'

type Operations={valuations:{review:number;draft:number};assignments:{paused:number;active:number};market:{pendingIdentity:number;confirmed:number};tasks:{open:number;overdue:number;urgent:number};errors:string[]}
type Task={id:string;title:string;status:string;priority:string;due_date:string|null;office:string|null;assignedProfile?:{full_name:string|null}|null}
export function CeoDecisions(){
 const [operations,setOperations]=useState<Operations|null>(null);const [tasks,setTasks]=useState<Task[]>([]);const [error,setError]=useState<string|null>(null)
 useEffect(()=>{void(async()=>{try{const [o,t]=await Promise.all([fetch('/api/management/ceo-operations',{cache:'no-store'}),fetch('/api/management/tasks',{cache:'no-store'})]);const [od,td]=await Promise.all([o.json(),t.json()]);if(!o.ok||!t.ok)throw new Error(od.error||td.error||'No fue posible cargar las decisiones.');setOperations(od);setTasks(td.tasks??[])}catch(cause){setError(cause instanceof Error?cause.message:'Error de carga')}})()},[])
 const today=new Date().toISOString().slice(0,10);const pending=tasks.filter((task)=>['open','in_progress'].includes(task.status)).sort((a,b)=>{const av=a.due_date??'9999-12-31',bv=b.due_date??'9999-12-31';return av.localeCompare(bv)})
 return <IntelligencePage><Link href="/dashboard/ceo" className="inline-flex items-center gap-2 text-xs text-[var(--n3-text-muted)]"><ArrowLeft size={14}/>Volver al CEO</Link><IntelligenceHeader eyebrow="CEO · Centro de decisiones" title="Pendientes que requieren acción" description="Valorizaciones, tareas, asignaciones e identidad de mercado priorizadas para resolución." actions={[{label:'Valorizaciones',href:'/dashboard/valuations',primary:true},{label:'Tareas',href:'/dashboard/director/tareas'}]}/>{error?<div role="alert" className="border border-[#d7332b] p-5 text-[#ff766f]"><RefreshCw className="mb-2"/>{error}</div>:null}{!operations&&!error?<div role="status" className="border border-[var(--n3-line)] p-8 text-[var(--n3-text-muted)]">Cargando decisiones…</div>:null}{operations?<><section><SectionHeading eyebrow="01 · Carga crítica" title="Decisiones abiertas"/><MetricGrid columns={4}><MetricCard label="Valorizaciones en revisión" value={operations.valuations.review} detail={`${operations.valuations.draft} borradores`}/><MetricCard label="Tareas vencidas" value={operations.tasks.overdue} detail={`${operations.tasks.urgent} urgentes`}/><MetricCard label="Asignaciones pausadas" value={operations.assignments.paused} detail={`${operations.assignments.active} activas`}/><MetricCard label="Identidades pendientes" value={operations.market.pendingIdentity} detail={`${operations.market.confirmed} confirmadas`}/></MetricGrid></section><section><SectionHeading eyebrow="02 · Cola de seguimiento" title="Responsables y vencimientos"/><div className="space-y-3">{pending.length?pending.map((task)=><article key={task.id} className={`border bg-[#0c1111] p-4 ${task.due_date&&task.due_date<today?'border-[#d7332b]':task.priority==='urgent'?'border-[#a77a22]':'border-[var(--n3-line)]'}`}><div className="flex flex-col gap-3 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{task.title}</p><p className="mt-1 text-xs text-[var(--n3-text-muted)]">{task.office??'Sin oficina'} · {task.assignedProfile?.full_name??'Sin responsable'} · {task.status} · vence {task.due_date??'sin fecha'}</p></div><Link href="/dashboard/director/tareas" className="inline-flex items-center gap-2 text-xs text-[#ff766f]">Gestionar<ArrowRight size={13}/></Link></div></article>):<div className="border border-dashed border-[var(--n3-line)] p-6 text-sm text-[var(--n3-text-muted)]">No existen tareas abiertas.</div>}</div></section></>:null}</IntelligencePage>
}
