'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import PrintReportButton from '@/components/reports/print-report-button'
import { IntelligenceHeader, IntelligencePage, MethodologyNote, MetricCard, MetricGrid, SectionHeading } from '@/components/intelligence/design-system'

type Metric={code:string;label:string;unit:string;value:number|null;target:number|null;compliance:number|null;mom:number|null;yoy?:number|null}
type Evolution={period:string;sales:number|null;salesTarget:number|null}
type Entity={id:string;name:string;entityType:string;parentId:string|null;classification?:string|null;metrics:Metric[];evolution?:Evolution[]}
type Summary={periodLabel:string;generatedAt?:string;dataProvenance?:string;entities:Entity[]}
type Operations={valuations:{review:number;draft:number;approved:number;issued:number};assignments:{active:number;paused:number};market:{properties:number;confirmed:number;pendingIdentity:number};tasks:{open:number;overdue:number;urgent:number};generatedAt:string}
type Task={id:string;title:string;status:string;priority:string;due_date:string|null;office:string|null;assignedProfile?:{full_name:string|null}|null}
const metric=(entity:Entity|undefined,code:string)=>entity?.metrics.find((item)=>item.code===code)
const fmt=(item?:Metric)=>!item||item.value==null?'n/d':item.unit==='uf'?`${item.value.toLocaleString('es-CL',{maximumFractionDigits:0})} UF`:item.value.toLocaleString('es-CL',{maximumFractionDigits:1})
const pct=(value:number|null|undefined)=>value==null?'n/d':`${value>0?'+':''}${value.toFixed(1)}%`
const compliance=(item?:Metric)=>item?.compliance==null?'n/d':`${item.compliance.toFixed(1)}%`

export function CeoReport(){
  const [summary,setSummary]=useState<Summary|null>(null)
  const [operations,setOperations]=useState<Operations|null>(null)
  const [tasks,setTasks]=useState<Task[]>([])
  const [error,setError]=useState<string|null>(null)
  useEffect(()=>{void(async()=>{try{const [s,o,t]=await Promise.all([fetch('/api/management/summary',{cache:'no-store'}),fetch('/api/management/ceo-operations',{cache:'no-store'}),fetch('/api/management/tasks',{cache:'no-store'})]);const [sd,od,td]=await Promise.all([s.json(),o.json(),t.json()]);if(!s.ok||!o.ok||!t.ok)throw new Error(sd.error||od.error||td.error||'No fue posible generar el reporte.');setSummary(sd);setOperations(od);setTasks(td.tasks??[])}catch(cause){setError(cause instanceof Error?cause.message:'Error de reporte')}})()},[])
  const company=summary?.entities.find((entity)=>entity.entityType==='company')
  const branches=summary?.entities.filter((entity)=>entity.entityType==='branch')??[]
  const partners=summary?.entities.filter((entity)=>entity.entityType==='partner')??[]
  const openTasks=tasks.filter((task)=>['open','in_progress'].includes(task.status))
  const top=useMemo(()=>[...partners].sort((a,b)=>Number(metric(b,'sales')?.value??-1)-Number(metric(a,'sales')?.value??-1)).slice(0,10),[partners])
  const reportId=`CEO-${(summary?.generatedAt??new Date().toISOString()).slice(0,10).replaceAll('-','')}`
  const sales=metric(company,'sales');const salesUf=metric(company,'sales_uf');const followUp=metric(company,'follow_up_score');const conversion=metric(company,'conversion');const productivity=sales?.value!=null&&partners.length?sales.value/partners.length:null
  const priorityTasks=openTasks.filter((task)=>task.priority==='urgent'||(task.due_date&&task.due_date<new Date().toISOString().slice(0,10))).slice(0,12)
  return <IntelligencePage>
    <div className="print-hidden flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard/ceo" className="border border-[var(--n3-line)] px-4 py-2 text-xs focus-visible:outline focus-visible:outline-2">Volver al CEO</Link><PrintReportButton/></div>
    <IntelligenceHeader eyebrow="Reporte ejecutivo CEO · Alcance contractual" title="Property Partners · Consolidado" description="Resultados, captaciones, ventas, seguimiento, conversión, productividad, metas, variaciones, evolución, rankings y alertas." meta={<div className="text-xs text-[var(--n3-text-muted)]">ID {reportId}</div>}/>
    {error?<div role="alert" className="border border-[#d7332b] p-5 text-[#ff766f]">{error}</div>:null}
    {!error&&(!summary||!operations)?<div role="status" className="border border-[var(--n3-line)] p-8 text-sm text-[var(--n3-text-muted)]">Generando reporte…</div>:null}
    {!error&&summary&&operations?<>
      <section><SectionHeading eyebrow="01 · Resumen" title="Pulso de la compañía"/><MetricGrid columns={4}><MetricCard label="Ventas" value={fmt(sales)} detail={`Meta ${sales?.target??'n/d'} · ${compliance(sales)}`}/><MetricCard label="Venta UF" value={fmt(salesUf)} detail={`Cumplimiento ${compliance(salesUf)}`}/><MetricCard label="Productividad" value={productivity==null?'n/d':`${productivity.toFixed(2)} cierres/ejecutiva`} detail="Indicador derivado"/><MetricCard label="Alertas operativas" value={operations.tasks.overdue+operations.valuations.review} detail={`${operations.tasks.overdue} tareas vencidas · ${operations.valuations.review} valorizaciones`}/></MetricGrid></section>
      <section><SectionHeading eyebrow="02 · Cobertura contractual" title="Indicadores requeridos"/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Captaciones" value="n/d" detail="La fuente actual no las separa de stock"/><MetricCard label="Seguimiento" value={fmt(followUp)} detail="Score consolidado"/><MetricCard label="Conversión" value={fmt(conversion)} detail="Score consolidado"/><MetricCard label="Variaciones" value={`MoM ${pct(sales?.mom)}`} detail={`YoY ${pct(sales?.yoy)}`}/></div></section>
      <section><SectionHeading eyebrow="03 · Evolución" title="Ventas mensuales y meta"/>{company?.evolution?.length?<div className="overflow-x-auto border border-[var(--n3-line)]"><table className="w-full min-w-[720px] text-sm"><thead className="bg-[#080d0d] text-[10px] uppercase tracking-[0.12em] text-[var(--n3-text-muted)]"><tr><th className="px-4 py-3 text-left">Período</th><th className="px-4 py-3 text-right">Ventas</th><th className="px-4 py-3 text-right">Meta</th><th className="px-4 py-3 text-right">Cumplimiento</th></tr></thead><tbody>{company.evolution.map((item)=><tr key={item.period} className="border-t border-[var(--n3-line)]"><td className="px-4 py-3">{item.period}</td><td className="px-4 py-3 text-right">{item.sales??'n/d'}</td><td className="px-4 py-3 text-right">{item.salesTarget??'n/d'}</td><td className="px-4 py-3 text-right">{item.sales!=null&&item.salesTarget?`${((item.sales/item.salesTarget)*100).toFixed(1)}%`:'n/d'}</td></tr>)}</tbody></table></div>:<div className="border border-dashed border-[var(--n3-line)] p-5 text-sm text-[var(--n3-text-muted)]">Sin evolución canónica disponible.</div>}</section>
      <section><SectionHeading eyebrow="04 · Oficinas" title="Comparativo ejecutivo"/><div className="overflow-x-auto border border-[var(--n3-line)]"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-[#080d0d] text-[10px] uppercase tracking-[0.12em] text-[var(--n3-text-muted)]"><tr><th className="px-4 py-3 text-left">Oficina</th><th className="px-4 py-3 text-right">Ventas</th><th className="px-4 py-3 text-right">Cumpl.</th><th className="px-4 py-3 text-right">MoM</th><th className="px-4 py-3 text-right">YoY</th><th className="px-4 py-3 text-right">Seguimiento</th><th className="px-4 py-3 text-right">Conversión</th><th className="px-4 py-3 text-right">Productividad</th></tr></thead><tbody>{branches.map((branch)=>{const branchSales=metric(branch,'sales');const branchPartners=partners.filter((partner)=>partner.parentId===branch.id);const branchProductivity=branchSales?.value!=null&&branchPartners.length?branchSales.value/branchPartners.length:null;return <tr key={branch.id} className="border-t border-[var(--n3-line)]"><td className="px-4 py-3 font-semibold">{branch.name}</td><td className="px-4 py-3 text-right">{fmt(branchSales)}</td><td className="px-4 py-3 text-right">{compliance(branchSales)}</td><td className="px-4 py-3 text-right">{pct(branchSales?.mom)}</td><td className="px-4 py-3 text-right">{pct(branchSales?.yoy)}</td><td className="px-4 py-3 text-right">{fmt(metric(branch,'follow_up_score'))}</td><td className="px-4 py-3 text-right">{fmt(metric(branch,'conversion'))}</td><td className="px-4 py-3 text-right">{branchProductivity==null?'n/d':branchProductivity.toFixed(2)}</td></tr>})}</tbody></table></div></section>
      <section className="grid gap-5 xl:grid-cols-2"><div><SectionHeading eyebrow="05 · Ranking" title="Top ejecutivas por ventas"/><div className="divide-y divide-[var(--n3-line)] border border-[var(--n3-line)]">{top.map((entity,index)=><div key={entity.id} className="flex items-center justify-between p-4"><div><span className="mr-3 text-xs text-[var(--n3-text-muted)]">{index+1}</span><strong>{entity.name}</strong></div><span>{fmt(metric(entity,'sales'))}</span></div>)}</div></div><div><SectionHeading eyebrow="06 · Alertas" title={operations.tasks.overdue+operations.valuations.review+operations.assignments.paused+operations.market.pendingIdentity?'Pendientes activos':'Sin pendientes críticos'}/><div className="space-y-3"><article className="border border-[var(--n3-line)] p-4">{operations.tasks.overdue} tareas vencidas · {operations.tasks.urgent} urgentes</article><article className="border border-[var(--n3-line)] p-4">{operations.valuations.review} valorizaciones en revisión</article><article className="border border-[var(--n3-line)] p-4">{operations.assignments.paused} asignaciones pausadas</article><article className="border border-[var(--n3-line)] p-4">{operations.market.pendingIdentity} identidades pendientes</article></div></div></section>
      <section><SectionHeading eyebrow="07 · Seguimiento" title="Tareas prioritarias"/><div className="space-y-3">{priorityTasks.map((task)=><article key={task.id} className="border border-[var(--n3-line)] p-4"><p className="font-semibold">{task.title}</p><p className="mt-1 text-xs text-[var(--n3-text-muted)]">{task.office??'Sin oficina'} · {task.assignedProfile?.full_name??'Sin responsable'} · vence {task.due_date??'sin fecha'}</p></article>)}{!priorityTasks.length?<div className="border border-dashed border-[var(--n3-line)] p-5 text-sm text-[var(--n3-text-muted)]">Sin tareas urgentes o vencidas.</div>:null}</div></section>
      <MethodologyNote>Reporte {reportId}. Período {summary.periodLabel}. Generado {new Date(operations.generatedAt).toLocaleString('es-CL')}. {summary.dataProvenance} Captaciones y YoY permanecen n/d cuando la fuente no los entrega. Productividad se calcula como ventas divididas por ejecutivas con ficha canónica.</MethodologyNote>
    </>:null}
  </IntelligencePage>
}
