'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { AlertTriangle, ArrowLeft, Building2, RefreshCw } from 'lucide-react'

type Metric={code:string;value:number|null;target:number|null;compliance:number|null;mom:number|null;yoy?:number|null;unit:string}
type Evolution={period:string;sales:number|null;salesTarget:number|null}
type Entity={id:string;name:string;entityType:string;parentId:string|null;metrics:Metric[];evolution?:Evolution[]}
type Summary={periodLabel:string;generatedAt?:string;entities:Entity[]}
type Operations={valuations:{review:number};tasks:{overdue:number;urgent:number};assignments:{paused:number};market:{pendingIdentity:number}}
const metric=(entity:Entity|undefined,code:string)=>entity?.metrics.find((item)=>item.code===code)
const fmt=(item?:Metric)=>!item||item.value==null?'n/d':item.unit==='uf'?`${item.value.toLocaleString('es-CL',{maximumFractionDigits:0})} UF`:item.value.toLocaleString('es-CL',{maximumFractionDigits:1})
const pct=(value:number|null|undefined)=>value==null?'n/d':`${value>0?'+':''}${value.toFixed(1)}%`
const compliance=(item?:Metric)=>item?.compliance==null?'n/d':`${item.compliance.toFixed(1)}%`

export function CeoPresentation(){
  const [summary,setSummary]=useState<Summary|null>(null)
  const [operations,setOperations]=useState<Operations|null>(null)
  const [error,setError]=useState<string|null>(null)
  useEffect(()=>{void(async()=>{try{const [s,o]=await Promise.all([fetch('/api/management/summary',{cache:'no-store'}),fetch('/api/management/ceo-operations',{cache:'no-store'})]);const [sd,od]=await Promise.all([s.json(),o.json()]);if(!s.ok||!o.ok)throw new Error(sd.error||od.error||'No fue posible cargar la presentación.');setSummary(sd);setOperations(od)}catch(cause){setError(cause instanceof Error?cause.message:'Error de carga')}})()},[])
  const company=summary?.entities.find((entity)=>entity.entityType==='company')
  const branches=summary?.entities.filter((entity)=>entity.entityType==='branch')??[]
  const partners=summary?.entities.filter((entity)=>entity.entityType==='partner')??[]
  const ordered=useMemo(()=>[...branches].sort((a,b)=>Number(metric(b,'sales')?.compliance??-1)-Number(metric(a,'sales')?.compliance??-1)),[branches])
  const ranking=useMemo(()=>[...partners].sort((a,b)=>Number(metric(b,'sales')?.value??-1)-Number(metric(a,'sales')?.value??-1)).slice(0,5),[partners])
  const sales=metric(company,'sales');const followUp=metric(company,'follow_up_score');const conversion=metric(company,'conversion');const productivityProxy=sales?.value!=null&&partners.length?sales.value/partners.length:null
  const evolution=company?.evolution??[];const max=Math.max(1,...evolution.flatMap((item)=>[item.sales??0,item.salesTarget??0]))
  const actionPending=operations?operations.tasks.overdue+operations.valuations.review+operations.assignments.paused:0
  const dataBacklog=operations?.market.pendingIdentity??0
  return <main className="min-h-screen bg-[var(--n3-black)] px-5 py-6 text-[var(--n3-text-light)] md:px-10 lg:px-14">
    <div className="mb-8 flex flex-wrap items-center justify-between gap-4"><Link href="/dashboard/ceo" className="inline-flex items-center gap-2 text-sm text-[var(--n3-text-muted)] focus-visible:outline focus-visible:outline-2"><ArrowLeft size={16}/>Volver</Link><div className="text-xs uppercase tracking-[0.16em] text-[var(--n3-text-muted)]">{summary?.periodLabel??'Cargando período'} · {summary?.generatedAt?new Date(summary.generatedAt).toLocaleString('es-CL'):'sin actualización'}</div></div>
    {error?<div role="alert" className="border border-[#d7332b] p-6 text-[#ff766f]"><RefreshCw className="mb-3"/>{error}</div>:null}
    {!error&&(!summary||!operations)?<div role="status" className="flex min-h-[60vh] items-center justify-center text-lg text-[var(--n3-text-muted)]">Preparando vista ejecutiva…</div>:null}
    {!error&&summary&&operations?<>
      <header className="mb-10 max-w-5xl"><div className="mb-4 flex items-center gap-3 text-sm uppercase tracking-[0.18em] text-[#ff766f]"><Building2 size={20}/>Presentación ejecutiva contractual</div><h1 className="text-4xl font-semibold leading-tight md:text-6xl">Property Partners en una mirada</h1><p className="mt-5 max-w-4xl text-lg leading-8 text-[var(--n3-text-muted)]">Resultados consolidados y por oficina, metas, variaciones, evolución, productividad, seguimiento, conversión, ranking y alertas.</p></header>
      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article className="border border-[var(--n3-line)] bg-[#0c1111] p-6"><p className="text-sm text-[var(--n3-text-muted)]">Ventas (cierres)</p><p className="mt-3 text-4xl font-semibold">{fmt(sales)}</p><p className="mt-2 text-sm">Meta {sales?.target??'n/d'} · {compliance(sales)}</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-6"><p className="text-sm text-[var(--n3-text-muted)]">Variaciones</p><p className="mt-3 text-3xl font-semibold">MoM {pct(sales?.mom)}</p><p className="mt-2 text-sm text-[var(--n3-text-muted)]">YoY {pct(sales?.yoy)}</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-6"><p className="text-sm text-[var(--n3-text-muted)]">Productividad (proxy)</p><p className="mt-3 text-3xl font-semibold">{productivityProxy==null?'n/d':productivityProxy.toFixed(2)}</p><p className="mt-2 text-sm text-[var(--n3-text-muted)]">Cierres ÷ fichas canónicas visibles; no equivale a dotación total.</p></article><article className={`border bg-[#0c1111] p-6 ${actionPending?'border-[#a77a22]':'border-[#2f8f4e]'}`}><p className="text-sm text-[var(--n3-text-muted)]">Decisiones operativas</p><p className="mt-3 text-4xl font-semibold">{actionPending}</p><p className="mt-2 text-sm text-[var(--n3-text-muted)]">Excluye backlog de calidad de datos.</p></article></section>
      <section className="mt-10 grid gap-4 md:grid-cols-3"><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Captaciones</p><p className="mt-3 text-3xl font-semibold">n/d</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">La fuente actual no entrega captaciones separadas de stock.</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Seguimiento</p><p className="mt-3 text-3xl font-semibold">{fmt(followUp)}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">Score canónico, no tasa porcentual.</p></article><article className="border border-[var(--n3-line)] bg-[#0c1111] p-5"><p className="text-sm text-[var(--n3-text-muted)]">Conversión</p><p className="mt-3 text-3xl font-semibold">{fmt(conversion)}</p><p className="mt-2 text-xs text-[var(--n3-text-muted)]">Score canónico, no tasa porcentual.</p></article></section>
      <section className="mt-10"><h2 className="mb-5 text-2xl font-semibold">Evolución ventas / meta</h2>{evolution.length?<div className="grid grid-cols-6 gap-3 border border-[var(--n3-line)] bg-[#0c1111] p-5">{evolution.map((item)=><div key={item.period} className="flex min-h-44 flex-col justify-end"><div className="flex h-28 items-end justify-center gap-1"><div className="w-5 bg-[#d7332b]" style={{height:`${Math.max(3,((item.sales??0)/max)*100)}%`}}/><div className="w-5 bg-white/15" style={{height:`${Math.max(3,((item.salesTarget??0)/max)*100)}%`}}/></div><p className="mt-2 text-center text-xs uppercase text-[var(--n3-text-muted)]">{item.period.slice(5)}</p><p className="text-center text-sm">{item.sales??'n/d'} / {item.salesTarget??'n/d'}</p></div>)}</div>:<div className="border border-dashed border-[var(--n3-line)] p-6 text-[var(--n3-text-muted)]">Sin evolución canónica disponible.</div>}</section>
      <section className="mt-10"><h2 className="mb-5 text-2xl font-semibold">Ranking de oficinas</h2><div className="grid gap-4 lg:grid-cols-3">{ordered.map((branch,index)=><article key={branch.id} className="border border-[var(--n3-line)] bg-[#0c1111] p-6"><div className="flex justify-between"><span className="text-xs text-[var(--n3-text-muted)]">#{index+1}</span><span>{compliance(metric(branch,'sales'))}</span></div><h3 className="mt-3 text-2xl font-semibold">{branch.name}</h3><p className="mt-4 text-3xl font-semibold">{fmt(metric(branch,'sales'))}</p><div className="mt-5 grid grid-cols-2 gap-3"><div><p className="text-xs text-[var(--n3-text-muted)]">Seguimiento (score)</p><p className="text-xl">{fmt(metric(branch,'follow_up_score'))}</p></div><div><p className="text-xs text-[var(--n3-text-muted)]">Conversión (score)</p><p className="text-xl">{fmt(metric(branch,'conversion'))}</p></div></div></article>)}</div></section>
      <section className="mt-10 grid gap-5 lg:grid-cols-[1fr_0.8fr]"><div><h2 className="mb-5 text-2xl font-semibold">Top ejecutivas por cierres</h2><div className="divide-y divide-[var(--n3-line)] border border-[var(--n3-line)] bg-[#0c1111]">{ranking.map((entity,index)=><div key={entity.id} className="flex justify-between p-4"><span>{index+1}. {entity.name}</span><strong>{fmt(metric(entity,'sales'))}</strong></div>)}</div></div><article className={`border bg-[#0c1111] p-7 ${actionPending?'border-[#a77a22]':'border-[#2f8f4e]'}`}><div className="flex gap-4"><AlertTriangle className={actionPending?'text-[#f6c453]':'text-[#65c780]'}/><div><h2 className="text-2xl font-semibold">{actionPending?'Decisiones inmediatas':'Operación sin decisiones vencidas'}</h2><p className="mt-3 text-lg leading-8 text-[var(--n3-text-muted)]">{operations.tasks.overdue} tareas vencidas, {operations.valuations.review} valorizaciones y {operations.assignments.paused} asignaciones pausadas.</p><p className="mt-3 text-sm text-[var(--n3-text-muted)]">Backlog de calidad de datos: {dataBacklog} registros de mercado sin identidad confirmada.</p></div></div></article></section>
      <p className="mt-8 text-xs leading-5 text-[var(--n3-text-muted)]">Los consolidados y las oficinas se reproducen desde sus fuentes canónicas respectivas; no se fuerza que el total de compañía sea la suma de láminas de oficina. Las alertas usan un umbral operativo derivado de 70 puntos.</p>
    </>:null}
  </main>
}
