'use client'

import { useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import PrintReportButton from '@/components/reports/print-report-button'
import { IntelligenceHeader, IntelligencePage, MethodologyNote, MetricCard, MetricGrid, SectionHeading } from '@/components/intelligence/design-system'

type Metric={code:string;label:string;unit:string;value:number|null;target:number|null;compliance:number|null;mom:number|null;yoy:number|null;comparisonValue?:number|null;comparisonPeriod?:string|null;qualityNotes?:string[];methodology?:string}
type Evolution={period:string;sales:number|null;salesTarget:number|null}
type Entity={id:string;name:string;entityType:string;parentId:string|null;classification?:string|null;metrics:Metric[];evolution?:Evolution[]}
type Summary={periodLabel:string;generatedAt?:string;dataProvenance?:string;entities:Entity[]}
type Operations={valuations:{review:number;draft:number;approved:number;issued:number};assignments:{active:number;paused:number};market:{properties:number;confirmed:number;pendingIdentity:number};tasks:{open:number;overdue:number;urgent:number};generatedAt:string}
type Task={id:string;title:string;status:string;priority:string;due_date:string|null;office:string|null;assignedProfile?:{full_name:string|null}|null}
const metric=(entity:Entity|undefined,code:string)=>entity?.metrics.find((item)=>item.code===code)
const fmt=(item?:Metric)=>!item||item.value==null?'n/d':item.unit==='uf'?`${item.value.toLocaleString('es-CL',{maximumFractionDigits:0})} UF`:item.value.toLocaleString('es-CL',{maximumFractionDigits:1})
const pct=(value:number|null|undefined)=>value==null?'n/d':`${value>0?'+':''}${value.toFixed(1)}%`
const compliance=(item?:Metric)=>item?.compliance==null?'n/d':`${item.compliance.toFixed(1)}%`
const base=(item?:Metric)=>item?.comparisonValue==null?'n/d':item.unit==='uf'?`${item.comparisonValue.toLocaleString('es-CL',{maximumFractionDigits:0})} UF`:item.comparisonValue.toLocaleString('es-CL',{maximumFractionDigits:1})

export function CeoReport(){
  const [summary,setSummary]=useState<Summary|null>(null),[operations,setOperations]=useState<Operations|null>(null),[tasks,setTasks]=useState<Task[]>([]),[error,setError]=useState<string|null>(null)
  useEffect(()=>{void(async()=>{try{const [s,o,t]=await Promise.all([fetch('/api/management/summary',{cache:'no-store'}),fetch('/api/management/ceo-operations',{cache:'no-store'}),fetch('/api/management/tasks',{cache:'no-store'})]);const [sd,od,td]=await Promise.all([s.json(),o.json(),t.json()]);if(!s.ok||!o.ok||!t.ok)throw new Error(sd.error||od.error||td.error||'No fue posible generar el reporte.');setSummary(sd);setOperations(od);setTasks(td.tasks??[])}catch(cause){setError(cause instanceof Error?cause.message:'Error de reporte')}})()},[])
  const company=summary?.entities.find((entity)=>entity.entityType==='company'),branches=summary?.entities.filter((entity)=>entity.entityType==='branch')??[],partners=summary?.entities.filter((entity)=>entity.entityType==='partner')??[]
  const openTasks=tasks.filter((task)=>['open','in_progress'].includes(task.status)),top=useMemo(()=>[...partners].sort((a,b)=>Number(metric(b,'sales')?.value??-1)-Number(metric(a,'sales')?.value??-1)).slice(0,10),[partners])
  const reportId=`CEO-${(summary?.generatedAt??new Date().toISOString()).slice(0,10).replaceAll('-','')}`
  const sales=metric(company,'sales'),salesUf=metric(company,'sales_uf'),cum=metric(company,'cumulative_sales'),cumUf=metric(company,'cumulative_sales_uf'),stock=metric(company,'stock'),movement=metric(company,'portfolio_net_change'),followUp=metric(company,'follow_up_score'),conversion=metric(company,'conversion')
  const productivityProxy=sales?.value!=null&&partners.length?sales.value/partners.length:null
  const priorityTasks=openTasks.filter((task)=>task.priority==='urgent'||(task.due_date&&task.due_date<new Date().toISOString().slice(0,10))).slice(0,12)
  const actionPending=operations?operations.tasks.overdue+operations.valuations.review+operations.assignments.paused:0
  const qualityNotes=[...(sales?.qualityNotes??[]),...(salesUf?.qualityNotes??[]),...(cum?.qualityNotes??[]),...(cumUf?.qualityNotes??[])]
  return <IntelligencePage>
    <div className="print-hidden flex flex-wrap items-center justify-between gap-3"><Link href="/dashboard/ceo" className="border border-[var(--n3-line)] px-4 py-2 text-xs focus-visible:outline focus-visible:outline-2">Volver al CEO</Link><PrintReportButton/></div>
    <IntelligenceHeader eyebrow="Reporte ejecutivo CEO · Evidencia canónica" title="Property Partners · Consolidado 2026 vs 2025" description="Resultados, bases comparables, metas, cartera, evolución, rankings, alertas y decisiones." meta={<div className="text-xs text-[var(--n3-text-muted)]">ID {reportId}</div>}/>
    {error?<div role="alert" className="border border-[#d7332b] p-5 text-[#ff766f]">{error}</div>:null}{!error&&(!summary||!operations)?<div role="status" className="border border-[var(--n3-line)] p-8 text-sm text-[var(--n3-text-muted)]">Generando reporte…</div>:null}
    {!error&&summary&&operations?<>
      <section><SectionHeading eyebrow="01 · Resultado" title="Comparación canónica"/><MetricGrid columns={4}><MetricCard label="Cierres junio" value={fmt(sales)} detail={`2025: ${base(sales)} · YoY ${pct(sales?.yoy)}`}/><MetricCard label="UF junio" value={fmt(salesUf)} detail={`2025: ${base(salesUf)} · YoY ${pct(salesUf?.yoy)}`}/><MetricCard label="Cierres acumulados" value={fmt(cum)} detail={`2025: ${base(cum)} · YoY ${pct(cum?.yoy)}`}/><MetricCard label="UF acumuladas" value={fmt(cumUf)} detail={`2025: ${base(cumUf)} · YoY ${pct(cumUf?.yoy)}`}/></MetricGrid></section>
      <section><SectionHeading eyebrow="02 · Gestión" title="Metas, cartera y cobertura contractual"/><MetricGrid columns={4}><MetricCard label="Cumplimiento cierres" value={compliance(sales)} detail={`Meta junio ${sales?.target??'n/d'}`}/><MetricCard label="Cartera actual" value={fmt(stock)} detail={stock?.comparisonValue==null?'Mayo n/d':`Mayo: ${stock.comparisonValue.toLocaleString('es-CL')}`}/><MetricCard label="Movimiento neto cartera" value={fmt(movement)} detail={`${pct(movement?.yoy)} mayo–junio; no equivale a captaciones`}/><MetricCard label="Captaciones brutas" value="n/d" detail="No existe métrica explícita separada"/><MetricCard label="Seguimiento" value={fmt(followUp)} detail="Score canónico"/><MetricCard label="Conversión" value={fmt(conversion)} detail="Score canónico"/><MetricCard label="Productividad proxy" value={productivityProxy==null?'n/d':`${productivityProxy.toFixed(2)} cierres/ficha`} detail="No representa dotación total"/><MetricCard label="Decisiones operativas" value={actionPending} detail={`${operations.tasks.overdue} tareas · ${operations.valuations.review} valorizaciones · ${operations.assignments.paused} asignaciones`}/></MetricGrid></section>
      <section><SectionHeading eyebrow="03 · Evolución" title="Cierres mensuales y meta"/>{company?.evolution?.length?<div className="overflow-x-auto border border-[var(--n3-line)]"><table className="w-full min-w-[720px] text-sm"><thead className="bg-[#080d0d] text-[10px] uppercase tracking-[0.12em] text-[var(--n3-text-muted)]"><tr><th className="px-4 py-3 text-left">Período</th><th className="px-4 py-3 text-right">Cierres</th><th className="px-4 py-3 text-right">Meta</th><th className="px-4 py-3 text-right">Cumplimiento</th></tr></thead><tbody>{company.evolution.map((item)=><tr key={item.period} className="border-t border-[var(--n3-line)]"><td className="px-4 py-3">{item.period}</td><td className="px-4 py-3 text-right">{item.sales??'n/d'}</td><td className="px-4 py-3 text-right">{item.salesTarget??'n/d'}</td><td className="px-4 py-3 text-right">{item.sales!=null&&item.salesTarget?`${((item.sales/item.salesTarget)*100).toFixed(1)}%`:'n/d'}</td></tr>)}</tbody></table></div>:<div className="border border-dashed border-[var(--n3-line)] p-5 text-sm text-[var(--n3-text-muted)]">Sin evolución canónica disponible.</div>}</section>
      <section><SectionHeading eyebrow="04 · Oficinas" title="Comparativo con base 2025"/><div className="overflow-x-auto border border-[var(--n3-line)]"><table className="w-full min-w-[1320px] text-sm"><thead className="bg-[#080d0d] text-[10px] uppercase tracking-[0.12em] text-[var(--n3-text-muted)]"><tr><th className="px-4 py-3 text-left">Oficina</th><th className="px-4 py-3 text-right">Cierres 2026</th><th className="px-4 py-3 text-right">Cierres 2025</th><th className="px-4 py-3 text-right">YoY junio</th><th className="px-4 py-3 text-right">YoY acumulado</th><th className="px-4 py-3 text-right">UF YoY</th><th className="px-4 py-3 text-right">Cartera</th><th className="px-4 py-3 text-right">Mov. neto</th><th className="px-4 py-3 text-right">Seguimiento</th><th className="px-4 py-3 text-right">Conversión</th></tr></thead><tbody>{branches.map((branch)=>{const s=metric(branch,'sales'),u=metric(branch,'sales_uf'),c=metric(branch,'cumulative_sales'),st=metric(branch,'stock'),mv=metric(branch,'portfolio_net_change');return <tr key={branch.id} className="border-t border-[var(--n3-line)]"><td className="px-4 py-3 font-semibold">{branch.name}</td><td className="px-4 py-3 text-right">{fmt(s)}</td><td className="px-4 py-3 text-right">{base(s)}</td><td className="px-4 py-3 text-right">{pct(s?.yoy)}</td><td className="px-4 py-3 text-right">{pct(c?.yoy)}</td><td className="px-4 py-3 text-right">{pct(u?.yoy)}</td><td className="px-4 py-3 text-right">{fmt(st)}</td><td className="px-4 py-3 text-right">{fmt(mv)}</td><td className="px-4 py-3 text-right">{fmt(metric(branch,'follow_up_score'))}</td><td className="px-4 py-3 text-right">{fmt(metric(branch,'conversion'))}</td></tr>})}</tbody></table></div></section>
      <section className="grid gap-5 xl:grid-cols-2"><div><SectionHeading eyebrow="05 · Ranking" title="Top ejecutivas por cierres"/><div className="divide-y divide-[var(--n3-line)] border border-[var(--n3-line)]">{top.map((entity,index)=><div key={entity.id} className="flex items-center justify-between p-4"><div><span className="mr-3 text-xs text-[var(--n3-text-muted)]">{index+1}</span><strong>{entity.name}</strong></div><span>{fmt(metric(entity,'sales'))} · YoY {pct(metric(entity,'sales')?.yoy)}</span></div>)}</div></div><div><SectionHeading eyebrow="06 · Calidad" title={qualityNotes.length?'Observaciones de conciliación':'YoY conciliado'}/><div className="space-y-3">{qualityNotes.length?qualityNotes.map((note,index)=><article key={index} className="border border-[#a77a22] p-4 text-sm">{note}</article>):<article className="border border-[#2f8f4e] p-4 text-sm">El YoY recalculado coincide con el Δ% AA informado dentro de tolerancia.</article>}<article className="border border-[var(--n3-line)] p-4">Backlog de calidad de datos: {operations.market.pendingIdentity} registros sin identidad confirmada.</article></div></div></section>
      <section><SectionHeading eyebrow="07 · Seguimiento" title="Tareas prioritarias"/><div className="space-y-3">{priorityTasks.map((task)=><article key={task.id} className="border border-[var(--n3-line)] p-4"><p className="font-semibold">{task.title}</p><p className="mt-1 text-xs text-[var(--n3-text-muted)]">{task.office??'Sin oficina'} · {task.assignedProfile?.full_name??'Sin responsable'} · vence {task.due_date??'sin fecha'}</p></article>)}{!priorityTasks.length?<div className="border border-dashed border-[var(--n3-line)] p-5 text-sm text-[var(--n3-text-muted)]">Sin tareas urgentes o vencidas.</div>:null}</div></section>
      <MethodologyNote>Reporte {reportId}. Período {summary.periodLabel}. Generado {new Date(operations.generatedAt).toLocaleString('es-CL')}. {summary.dataProvenance} YoY recalculado desde bases 2025 y contrastado con Δ% AA. La variación de cartera es neta y no representa captaciones brutas. Los consolidados y oficinas mantienen sus fuentes respectivas.</MethodologyNote>
    </>:null}
  </IntelligencePage>
}
