import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'

test('core product surfaces keep decision content first and technical detail disclosed', () => {
  const ceo = readFileSync('components/management/ceo-dashboard-command.tsx', 'utf8')
  const august = readFileSync('components/management/august-board-reading.tsx', 'utf8')
  const market = readFileSync('app/dashboard/market/page.tsx', 'utf8')
  const valuations = readFileSync('app/dashboard/valuations/page.tsx', 'utf8')
  const management = readFileSync('app/dashboard/control/operations/page.tsx', 'utf8')
  const reports = readFileSync('app/dashboard/reportes/canonicos/page.tsx', 'utf8')
  const properties = readFileSync('app/dashboard/properties/page.tsx', 'utf8')
  const propertyReview = readFileSync('components/properties/property-review-inbox.tsx', 'utf8')
  const navigation = readFileSync('lib/navigation.ts', 'utf8')
  const offer = readFileSync('app/dashboard/market/oferta/page.tsx', 'utf8')
  const pedro = readFileSync('components/intelligence/pedro-pablo-workspace-v2.tsx', 'utf8')
  const floatingPedro = readFileSync('components/intelligence/pedro-pablo-floating-chat.tsx', 'utf8')
  const director = readFileSync('components/management/director-dashboard-v3.tsx', 'utf8')
  const partner = readFileSync('components/management/partner-performance-summary.tsx', 'utf8')
  const valuation = readFileSync('app/dashboard/valuation/page.tsx', 'utf8')
  const sidebar = readFileSync('components/layout/sidebar.tsx', 'utf8')
  const dataLayer = readFileSync('components/management/data-layer-legend.tsx', 'utf8')
  const directorOps = readFileSync('components/management/director-operational-workspace.tsx', 'utf8')
  const partnerOps = readFileSync('components/management/partner-operational-workspace.tsx', 'utf8')
  const publicHome = readFileSync('app/page.tsx', 'utf8')
  const publicEstimator = readFileSync('components/public/public-valuation-estimator.tsx', 'utf8')
  const boardReport = readFileSync('app/dashboard/reportes/directorio/page.tsx', 'utf8')
  const managementReport = readFileSync('app/dashboard/control/reports/[id]/page.tsx', 'utf8')
  const reportOperations = readFileSync('app/dashboard/reportes/operacion/page.tsx', 'utf8')
  const ceoReportGenerator = readFileSync('components/management/ceo-intelligence-report-generator.tsx', 'utf8')
  const contractualReportGenerator = readFileSync('components/management/canonical-latest-report-generator.tsx', 'utf8')
  const reportDelivery = readFileSync('components/management/report-delivery-console.tsx', 'utf8')
  const valuationCase = readFileSync('app/dashboard/valuations/[id]/page.tsx', 'utf8')
  const valuationIntelligence = readFileSync('components/valuation/valuation-decision-intelligence.tsx', 'utf8')
  const professionalReview = readFileSync('app/dashboard/valuations/[id]/professional-review/page.tsx', 'utf8')
  const login = readFileSync('app/auth/login/page.tsx', 'utf8')
  const globals = readFileSync('app/globals.css', 'utf8')

  assert.doesNotMatch(ceo, /Control Tower/)
  assert.match(ceo, /Requiere atención/)
  assert.match(ceo, /Ver todas las oficinas/)
  assert.match(ceo, /Ver calidad de datos/)
  assert.doesNotMatch(ceo, /Cargando datos canónicos/)

  assert.doesNotMatch(august, /SYS \/ CONTROL DE GESTIÓN/)
  assert.match(august, /Ver análisis de agosto/)

  assert.match(market, /Último inventario completo/)
  assert.match(market, /marketSourceLabel/)
  assert.match(market, /alertSeverityLabel/)
  assert.match(market, /Nuevas hoy/)
  assert.match(market, /Ver detalle de datos/)
  assert.match(market, /Ver evolución y gestión/)
  assert.doesNotMatch(market, /cron automático/)
  assert.doesNotMatch(market, /El KML es la autoridad territorial/)
  assert.doesNotMatch(market, /Territorio V1/)
  assert.doesNotMatch(market, /avisos live/)
  assert.doesNotMatch(market, /legacy →/)
  assert.doesNotMatch(market, /benchmark territorial/)
  assert.match(market, /Cobertura territorial/)
  assert.match(market, /Avisos vigentes/)
  assert.doesNotMatch(market, /referencias técnicas repetidas/)
  assert.doesNotMatch(market, /repeticiones técnicas/)
  assert.doesNotMatch(market, /IDs únicos/)
  assert.doesNotMatch(market, /Balanced Scorecard/)
  assert.doesNotMatch(market, /04 · Evolución/)
  assert.doesNotMatch(market, /05 · Último mes verificado/)
  assert.doesNotMatch(market, /06 ·/)
  assert.doesNotMatch(market, /07 ·/)
  assert.doesNotMatch(market, /identidad externa/)
  assert.doesNotMatch(market, /candidato fuerte de identidad/)
  assert.match(market, /Confirmar barrio sugerido/)
  assert.match(market, /Propiedades consolidadas/)

  assert.match(valuations, /Último movimiento/)
  assert.match(valuations, /latestCaseUpdate/)
  assert.match(valuations, /Ver calidad de datos/)

  assert.match(management, /Qué falta para cerrar/)
  assert.match(management, /Actualizado/)
  assert.match(management, /Ver calidad de datos/)
  assert.match(management, /reportTypeLabel/)
  assert.match(management, /statusLabel/)
  assert.match(management, />Datos y cargas<\/summary>/)

  assert.match(reports, /Último informe disponible/)
  assert.match(reports, /reportPeriodLabel/)
  assert.match(reports, /reportTitleLabel/)
  assert.doesNotMatch(reports, /propertyPartnersTimeZoneLabel/)
  assert.match(reports, /Ver trazabilidad/)
  assert.match(reports, /Ver historial/)
  assert.match(reports, /Ver calidad de datos/)
  assert.doesNotMatch(reports, /informes canónicos falló/)
  assert.doesNotMatch(reports, /informe canónico listo/)
  assert.doesNotMatch(reports, /Costo técnico/)
  assert.doesNotMatch(reports, />Modelo</)
  assert.doesNotMatch(reports, />Versión</)
  assert.doesNotMatch(reports, />Costo de generación</)
  assert.match(reports, />Fuentes</)
  assert.match(reports, />Estado</)

  assert.match(properties, /Requiere decisión/)
  assert.match(properties, /Ver calidad de datos/)
  assert.doesNotMatch(properties, /Sin casas live verificables/)
  assert.doesNotMatch(properties, /Corte live/)
  assert.doesNotMatch(properties, /Actualizado en vivo/)
  assert.match(properties, /Actualizado al consultar/)

  assert.match(propertyReview, /Listas/)
  assert.match(propertyReview, /Sin coincidencia/)
  assert.match(propertyReview, /Mostrar más/)
  assert.match(propertyReview, /Referencia Portal/)
  assert.doesNotMatch(propertyReview, /Sin match/)
  assert.doesNotMatch(propertyReview, />48 h/)
  assert.doesNotMatch(propertyReview, /Candidato KML único/)
  assert.doesNotMatch(propertyReview, /señal territorial determinística/)

  assert.match(navigation, /label: 'Propiedades', href: '\/dashboard\/properties'/)
  assert.doesNotMatch(navigation, /label: 'Por resolver', href: '\/dashboard\/properties'/)

  assert.match(offer, /Cambios de hoy/)
  assert.match(offer, /Ver inventario completo/)
  assert.doesNotMatch(offer, /snapshot diario/i)
  assert.doesNotMatch(offer, /snapshot completo/i)
  assert.doesNotMatch(offer, />ID \{item\.sourceListingId\}<\/p>/)
  assert.match(offer, /Detalle disponible/)
  assert.match(offer, /Último inventario completo/)
  assert.match(offer, /Cambios actualizados/)
  assert.match(offer, /En inventario completo/)
  assert.doesNotMatch(offer, /Inventario verificado/)
  assert.doesNotMatch(offer, /Publicación vigente/)
  assert.doesNotMatch(offer, /Publicación Portal \$\{item\.sourceListingId\}/)

  assert.match(pedro, /Decisiones con datos verificados/)
  assert.match(pedro, /Ver detalle/)
  assert.match(pedro, /evidenceSourceLabel/)
  assert.match(pedro, /Actualizado \{evidenceCutoffLabel\(item\.cutoff\)\}/)
  assert.doesNotMatch(pedro, /usuario autenticado \+ capabilities \+ RLS/)
  assert.doesNotMatch(pedro, /\{item\.domain \?/)
  assert.doesNotMatch(pedro, /\{item\.reference \?/)
  assert.doesNotMatch(pedro, /¿Qué cambió esta mañana en el mercado\?/)
  assert.doesNotMatch(pedro, /Tarea creada y registrada · \$\{execution\.task\.id\}/)
  assert.match(pedro, /domainLabel/)
  assert.doesNotMatch(pedro, /Objeto:/)
  assert.doesNotMatch(pedro, /Origen:<\/span> \{actionPreview\.taskDraft\.sourceKey\}/)
  assert.doesNotMatch(pedro, /telemetría de entregas/)
  assert.doesNotMatch(pedro, /Cobertura operativa/)
  assert.match(pedro, /Datos disponibles/)
  assert.match(pedro, /Cómo decide Pedro Pablo/)

  assert.doesNotMatch(floatingPedro, /rounded-(?:full|xl|lg|md)/)
  assert.doesNotMatch(floatingPedro, /shadow-(?:xl|2xl)/)
  assert.doesNotMatch(floatingPedro, /hover:-translate-y/)
  assert.match(floatingPedro, /visibleEvidenceSource/)
  assert.doesNotMatch(floatingPedro, /\{item\.label\}<\/span> · \{item\.source\}/)
  assert.doesNotMatch(floatingPedro, /¿Qué cambió esta mañana en el mercado\?/)

  assert.match(director, /eyebrow="Hoy"/)
  assert.match(director, /Ver seguimiento y análisis/)
  assert.doesNotMatch(director, /01 · Pulso de la oficina/)

  assert.match(partner, /Mi desempeño/)
  assert.match(partner, /Ver detalle/)
  assert.doesNotMatch(partner, /Corte canónico vigente/)
  assert.doesNotMatch(partner, /Cargando datos canónicos/)

  assert.match(valuation, /title="Nueva valorización"/)
  assert.match(valuation, /Revisar estado/)
  assert.match(valuation, /Referencia sugerida confirmada/)
  assert.doesNotMatch(valuation, /Referencia Champion v5/)
  assert.doesNotMatch(valuation, /Funcionalidad V2 habilitada para N3uralia/)
  assert.doesNotMatch(valuation, /property-partners-valuation-v2/)
  assert.doesNotMatch(valuation, /Barrio canónico/)
  assert.doesNotMatch(valuation, /Dato canónico/)
  assert.doesNotMatch(valuation, /superficie canónica completa/)

  assert.doesNotMatch(sidebar, /Intelligence Platform/)

  assert.doesNotMatch(dataLayer, /junio 2026/)
  assert.doesNotMatch(dataLayer, /Supabase/)
  assert.doesNotMatch(dataLayer, /RLS/)
  assert.match(dataLayer, /último período aprobado disponible/)

  assert.doesNotMatch(directorOps, /alcance central/)
  assert.match(directorOps, /statusLabel/)
  assert.match(directorOps, /En revisión/)
  assert.doesNotMatch(partnerOps, /RLS al alcance personal/)
  assert.match(partnerOps, /statusLabel/)
  assert.match(partnerOps, /En curso/)

  assert.match(publicHome, /Cómo se calcula/)
  assert.doesNotMatch(publicHome, /KML/)
  assert.doesNotMatch(publicHome, /Piso mínimo de evidencia/)
  assert.match(publicEstimator, /Rango referencial/)
  assert.match(publicEstimator, /Ver detalle del cálculo/)
  assert.match(publicEstimator, /Referencia central/)
  assert.match(publicEstimator, /Actualizado \{dateTime\.format\(new Date\(result\.newestObservation\)\)\}/)
  assert.match(publicEstimator, /options\.find\(\(option\) => option\.coverageLevel === 'sector'\)/)

  assert.match(reportOperations, /Todo borrador requiere revisión/)
  assert.match(ceoReportGenerator, /Generar informe ejecutivo/)
  assert.match(ceoReportGenerator, /Incluye: resultados, oficinas, mercado, conversión, valorizaciones y decisiones/)
  assert.doesNotMatch(ceoReportGenerator, /Reportin · CEO Intelligence/)
  assert.doesNotMatch(ceoReportGenerator, /Generar CEO Intelligence/)
  assert.doesNotMatch(ceoReportGenerator, /mapa KML/)
  assert.doesNotMatch(ceoReportGenerator, /benchmarks/)

  assert.match(contractualReportGenerator, /Generar avance contractual/)
  assert.match(contractualReportGenerator, /validación del proyecto/)
  assert.doesNotMatch(contractualReportGenerator, /Reportin · entrega contractual/)
  assert.doesNotMatch(contractualReportGenerator, /UAT/)
  assert.doesNotMatch(contractualReportGenerator, /gestión canónica/)

  assert.match(reportDelivery, /Generación y entrega de informes/)
  assert.match(reportDelivery, /Entrega por correo/)
  assert.match(reportDelivery, /Informes recientes/)
  assert.match(reportDelivery, /periodLabel/)
  assert.doesNotMatch(reportDelivery, /Delivery Control/)
  assert.doesNotMatch(reportDelivery, /America\/Santiago/)
  assert.doesNotMatch(reportDelivery, /snapshot persistido/)
  assert.doesNotMatch(reportDelivery, /Proveedor activo:/)

  assert.match(boardReport, /Informe de Directorio/)
  assert.match(boardReport, /Presentación vs operación/)
  assert.match(boardReport, /Reproduce fuentes aprobadas/)
  assert.doesNotMatch(boardReport, /JSON trazable/)
  assert.doesNotMatch(boardReport, /SHA-256/)
  assert.doesNotMatch(boardReport, /Reporte automático de Directorio/)
  assert.doesNotMatch(boardReport, /PPT Directorio vs CRM/)
  assert.doesNotMatch(boardReport, /Determinístico/)

  assert.match(managementReport, /Gestión mensual/)
  assert.match(managementReport, /Vs\. mismo mes del año anterior/)
  assert.match(managementReport, /Sin período comparable disponible/)
  assert.doesNotMatch(managementReport, /Módulo III/)
  assert.doesNotMatch(managementReport, /canonicalizado/)
  assert.doesNotMatch(managementReport, /no scoring oficial/)
  assert.doesNotMatch(managementReport, /Identificador: \{report\.id\}/)
  assert.match(managementReport, /entityTypeLabel/)
  assert.match(managementReport, /qualityLabel/)
  assert.match(managementReport, /severityLabel/)
  assert.doesNotMatch(managementReport, /Sin mes anterior canónico comparable/)

  assert.match(valuationCase, /Decisión final/)
  assert.match(valuationCase, /verificación reforzada/)
  assert.match(valuationCase, /Ver análisis y respaldo/)
  assert.doesNotMatch(valuationCase, /DECISIÓN CEO/)
  assert.doesNotMatch(valuationCase, /requiere MFA/)
  assert.doesNotMatch(valuationCase, /KML canónico/)
  assert.doesNotMatch(valuationCase, /CEO autorizado/)

  assert.match(valuationIntelligence, /ANÁLISIS DE RESPALDO/)
  assert.match(valuationIntelligence, /Validación histórica/)
  assert.match(valuationIntelligence, /Rango de evidencia/)
  assert.doesNotMatch(valuationIntelligence, /Backtest y trazabilidad/)
  assert.doesNotMatch(valuationIntelligence, /MAPE no disponible/)
  assert.doesNotMatch(valuationIntelligence, /Rango \/ banda/)
  assert.doesNotMatch(valuationIntelligence, /Rango contractual persistido/)
  assert.doesNotMatch(valuationIntelligence, /Venta histórica del sujeto/)

  assert.match(professionalReview, /Ver análisis y respaldo/)
  assert.match(professionalReview, /Calidad de evidencia/)
  assert.doesNotMatch(professionalReview, /Ver detalle técnico y trazabilidad/)
  assert.doesNotMatch(professionalReview, /Calidad interna/)

  assert.match(login, /Ingresa con tu cuenta de Property Partners/)
  assert.doesNotMatch(login, /Acceso administrado internamente/)
  assert.doesNotMatch(login, /Inteligencia de mercado Vitacura/)
})

test('shared workspace metadata is sentence case and freshness is explicit', () => {
  const workspace = readFileSync('components/ui/workspace.tsx', 'utf8')

  assert.doesNotMatch(workspace, /meta \? <div className="[^"]*uppercase/)
  assert.match(workspace, /Actualizado/)
  assert.match(workspace, /Sin observaciones/)
})


test('global product canvas remains flat and non-decorative', () => {
  const globals = readFileSync('app/globals.css', 'utf8')
  assert.doesNotMatch(globals, /gradient\(/)
  assert.match(globals, /background: var\(--background\)/)
})
