import Link from 'next/link'
import { Download, ExternalLink, FileText, Plus } from 'lucide-react'
import { requirePageCapability } from '@/lib/access-guards'
import { createAdminClient } from '@/lib/supabase/admin'
import { DataStatusBar, MetricStrip, WorkspaceHeader, WorkspaceShell } from '@/components/ui/workspace'

type CanonicalDocumentRow = { id:string; title:string; content:string; tags:string[]|null; created_at:string }
type ReportRecord = { id:string; title:string; period:string; status:string; createdAt:string; pdfUrl:string|null; downloadUrl:string|null }
const asRecord=(v:unknown):Record<string,unknown>|null=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:null
const parseContent=(content:string)=>{try{return asRecord(JSON.parse(content))}catch{return null}}
const readRecord=(r:Record<string,unknown>|null,k:string)=>r?asRecord(r[k]):null
const readString=(r:Record<string,unknown>|null,k:string,f='')=>r&&typeof r[k]==='string'&&String(r[k]).trim()?String(r[k]):f
function formatDate(value:string){const d=new Date(value);return Number.isNaN(d.getTime())?value:new Intl.DateTimeFormat('es-CL',{dateStyle:'medium',timeStyle:'short'}).format(d)}
function formatPeriod(record:Record<string,unknown>|null){const p=readRecord(record,'period');const s=readString(p,'start');const e=readString(p,'end');return s&&e&&s!==e?`${s} — ${e}`:s||e||'Sin período'}
function getArtifactUrl(parsed:Record<string,unknown>|null,type:'pdf'|'download'){const artifacts=readRecord(parsed,'artifacts');const pdf=readRecord(artifacts,'pdf');const keys=type==='pdf'?['url','viewUrl','artifactUrl','path']:['downloadUrl','url','artifactUrl','path'];for(const key of keys){const value=readString(pdf,key);if(value.startsWith('/')||value.startsWith('https://'))return value}return null}
function normalizeStatus(parsed:Record<string,unknown>|null,tags:string[]|null){const delivery=readRecord(parsed,'delivery');const raw=readString(delivery,'status',tags?.includes('approved')?'approved':'draft');return ({draft:'Borrador',review:'En revisión',approved:'Aprobado',sent:'Enviado',resent:'Reenviado',registered:'Registrado'} as Record<string,string>)[raw.toLowerCase()]??raw}

export default async function CanonicalClientReportsPage(){
  await requirePageCapability('reports.global.read')
  const supabase=createAdminClient()
  const {data,error}=await supabase.from('knowledge_documents').select('id,title,content,tags,created_at').contains('tags',['n3uralia-client-report']).order('created_at',{ascending:false}).limit(48)
  const documents=error?[]:(data||[]) as CanonicalDocumentRow[]
  const reports:ReportRecord[]=documents.map(document=>{const parsed=parseContent(document.content);return{id:document.id,title:document.title,period:formatPeriod(parsed),status:normalizeStatus(parsed,document.tags),createdAt:document.created_at,pdfUrl:getArtifactUrl(parsed,'pdf'),downloadUrl:getArtifactUrl(parsed,'download')}})
  const current=reports[0]??null;const history=reports.slice(1);const missingArtifacts=reports.filter(r=>!r.pdfUrl&&!r.downloadUrl).length
  const status=error?'blocked':reports.length===0?'blocked':missingArtifacts>0?'partial':'ready'
  const cutoff=current?formatDate(current.createdAt):'—'
  return <WorkspaceShell>
    <WorkspaceHeader eyebrow="Informes" title="Informes canónicos" actions={[{label:'Crear informe',href:'/dashboard/reportes/crear',primary:true,icon:<Plus size={15}/>}]} />
    <MetricStrip items={[{label:'Registrados',value:reports.length},{label:'Vigente',value:current?current.status:'—'},{label:'Con PDF',value:reports.length-missingArtifacts},{label:'Historial',value:history.length}]} />
    <section className="mt-6"><div className="flex items-center justify-between border-b border-[var(--n3-line)] pb-2"><h2 className="text-[10px] uppercase tracking-[0.16em] text-[var(--n3-text-muted)]">Vigente</h2><span className="text-xs text-[var(--n3-text-muted)]">{current?current.status:'Sin informe'}</span></div>{current?<article className="grid gap-5 border-b border-[var(--n3-line)] py-5 md:grid-cols-[minmax(0,1fr)_auto] md:items-center"><div><p className="text-xs uppercase tracking-[0.12em] text-[var(--n3-text-muted)]">{current.period}</p><h2 className="mt-2 text-xl font-semibold">{current.title}</h2><p className="mt-2 text-xs text-[var(--n3-text-muted)]">Generado {formatDate(current.createdAt)}</p></div><div className="flex flex-wrap gap-2">{current.pdfUrl?<Link href={current.pdfUrl} target="_blank" className="inline-flex min-h-10 items-center gap-2 border border-[var(--n3-line)] px-4 text-xs"><ExternalLink size={14}/>Abrir</Link>:null}{current.downloadUrl?<Link href={current.downloadUrl} className="inline-flex min-h-10 items-center gap-2 border border-[var(--n3-line)] px-4 text-xs"><Download size={14}/>Descargar PDF</Link>:null}{!current.pdfUrl&&!current.downloadUrl?<span className="inline-flex min-h-10 items-center gap-2 border border-[var(--n3-line)] px-4 text-xs text-[var(--n3-text-muted)]"><FileText size={14}/>PDF no vinculado</span>:null}</div></article>:<div className="border-b border-[var(--n3-line)] py-8 text-sm text-[var(--n3-text-muted)]">No hay informes registrados.</div>}</section>
    <section className="mt-7"><div className="flex items-center justify-between border-b border-[var(--n3-line)] pb-2"><h2 className="text-[10px] uppercase tracking-[0.16em] text-[var(--n3-text-muted)]">Historial</h2><span className="text-xs tabular-nums text-[var(--n3-text-muted)]">{history.length}</span></div>{history.length?<div className="divide-y divide-[var(--n3-line)]">{history.map(report=><article key={report.id} className="grid gap-3 py-4 sm:grid-cols-[140px_minmax(0,1fr)_100px_auto] sm:items-center"><span className="text-xs text-[var(--n3-text-muted)]">{report.period}</span><div className="min-w-0"><p className="truncate text-sm font-medium">{report.title}</p><p className="mt-1 text-[11px] text-[var(--n3-text-muted)]">{formatDate(report.createdAt)}</p></div><span className="text-xs text-[var(--n3-text-muted)]">{report.status}</span><div className="flex justify-end gap-2">{report.pdfUrl?<Link href={report.pdfUrl} target="_blank" aria-label={`Abrir ${report.title}`} className="inline-flex h-9 w-9 items-center justify-center border border-[var(--n3-line)]"><ExternalLink size={14}/></Link>:null}{report.downloadUrl?<Link href={report.downloadUrl} aria-label={`Descargar ${report.title}`} className="inline-flex h-9 w-9 items-center justify-center border border-[var(--n3-line)]"><Download size={14}/></Link>:null}</div></article>)}</div>:<div className="py-6 text-sm text-[var(--n3-text-muted)]">Sin versiones anteriores.</div>}</section>
    <DataStatusBar cutoff={cutoff} coverage={reports.length?`${reports.length-missingArtifacts}/${reports.length} con artefacto PDF`:'Sin informes canónicos'} issues={error?1:missingArtifacts} status={status}/>
  </WorkspaceShell>
}
