export const MONTHLY_EXECUTIVE_REPORT_STANDARD = {
  version: '2026.08.25-v1',
  document: 'docs/reporting/MONTHLY_EXECUTIVE_REPORT_STANDARD.md',
  scope: 'Property Partners Vitacura monthly CEO management report',
  sourcePolicy: {
    metrics: 'public.management_metric_values',
    definitions: 'public.management_metric_definitions',
    entities: 'public.management_entities',
    goals: 'public.management_goals',
    evidence: [
      'public.management_source_records',
      'public.management_import_runs',
      'public.management_metric_reconciliations',
    ],
    forbiddenAsMonthlyKpiSource: [
      'public.weekly_reports',
      'market intelligence derived layers',
      'valuation derived layers',
      'hard-coded assumptions',
      'demo/mock data',
    ],
  },
  requiredMetrics: [
    'sales',
    'sales_uf',
    'goal_compliance',
    'requirements',
    'leads',
    'scheduled_visits',
    'realized_visits',
    'listings',
    'stock',
    'suspended_listings',
  ],
  optionalManagementMetrics: [
    'active_leads_snapshot',
    'classified_leads',
    'unclassified_leads',
    'stale_90_leads',
    'active_a_leads',
    'stale_15a_leads',
    'conversion',
    'conversion_6m_operational',
    'productivity',
    'sales_velocity',
    'canonical_portfolio_score',
    'canonical_follow_up_score',
    'canonical_conversion_score',
    'canonical_management_score',
  ],
  sectionOrder: [
    'ceo_summary',
    'mom_yoy',
    'commercial_funnel',
    'portfolio',
    'management_diagnosis_actions',
    'sources_coverage_methodology',
  ],
  maxPages: 6,
  maxExecutiveMessages: 3,
  maxActions: 3,
  comparisonPolicy: {
    mom: 'same metric, immediately previous calendar month, compatible formula_version',
    yoy: 'same metric, same calendar month previous year, compatible formula_version',
    missing: 'N/D',
    zeroDenominator: 'N/D',
  },
  funnel: [
    'requirements',
    'leads',
    'scheduled_visits',
    'realized_visits',
    'sales',
  ],
  derivedMetrics: {
    requirements_to_leads: ['leads', 'requirements'],
    leads_to_scheduled: ['scheduled_visits', 'leads'],
    scheduled_to_realized: ['realized_visits', 'scheduled_visits'],
    realized_to_sales: ['sales', 'realized_visits'],
    leads_to_sales: ['sales', 'leads'],
    average_ticket_uf: ['sales_uf', 'sales'],
  },
  narrativePolicy: {
    language: 'es',
    modes: ['HECHO', 'LECTURA', 'ACCION'],
    noUnsupportedBenchmarks: true,
    noMarketIntelligenceByDefault: true,
    noValuationByDefault: true,
  },
  visualPolicy: {
    designAuthority: 'DESIGN.md',
    page: 'A4 portrait',
    reportFont: 'Montserrat',
    accent: 'Property Partners red',
    squareCorners: true,
    gradients: false,
    glass: false,
    glow: false,
    chartNullAsZero: false,
    chartSourceNoteRequired: true,
  },
} as const

export type MonthlyExecutiveReportStandard = typeof MONTHLY_EXECUTIVE_REPORT_STANDARD
